import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import { ThemeContextProvider } from "../context/ThemeContext";
import { LanguageProvider, useLanguage } from "../context/useLanguage";
import "../styles/globals.css";
import "../styles/customs.css";
import type { AppProps } from "next/app";
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  createHttpLink,
} from "@apollo/client";
import Head from "next/head";
import { LangType } from "../interfaces/Elements";
import { setContext } from "@apollo/client/link/context";
import { BACKEND_URL } from "../lib/parameters";
import { LoginContextProvider } from "../context/useLogin";

const BACKEND_GRAPHQL_URL = BACKEND_URL + "/graphql";
const httpLink = createHttpLink({
  uri: BACKEND_GRAPHQL_URL,
});

const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token =
    typeof window !== undefined
      ? localStorage.getItem("racing-account") ?? ""
      : "";
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      // authorization: token ? `Bearer ${token}` : "",
      Authorization: token,
    },
  };
});

console.log("connecting to backend at ", BACKEND_URL);
const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache({
    addTypename: false,
  }),
});

export default function App({ Component, pageProps }: AppProps) {
  const { lang } = useLanguage();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>{lang == LangType.EN ? "NTU Racing" : "台大賽車隊"}</title>
      </Head>
      <LoginContextProvider>
        <LanguageProvider>
          <ThemeContextProvider>
            <ApolloProvider client={client}>
              <NavBar />
              <Component {...pageProps} />
              <Footer />
            </ApolloProvider>
          </ThemeContextProvider>
        </LanguageProvider>
      </LoginContextProvider>
    </>
  );
}
